version: '3.1'

volumes:
  database-users:
  database-moments:
  database-friends:

services:
  api:
    image: da
    network_mode: "host"
  web:
    image: dsn
    network_mode: "host"
  users_db:
    image: postgres:13.1
    environment: 
      - POSTGRES_USER=cuzkov
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users_db
    ports: 
      - 45000:5432
    volumes:
      - database-users:/var/lib/postgresql/data/
  moments_db:
    image: postgres:13.1
    environment: 
      - POSTGRES_USER=cuzkov
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=moments_db
    ports: 
      - 45001:5432
    volumes:
      - database-moments:/var/lib/postgresql/data/
  friends_db:
    image: postgres:13.1
    environment: 
      - POSTGRES_USER=cuzkov
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=friends_db
    ports: 
      - 45002:5432
    volumes:
      - database-friends:/var/lib/postgresql/data/
