# Generated by Django 3.1 on 2020-10-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('user_id', models.PositiveIntegerField()),
                ('creation_date', models.DateField()),
                ('date_of_update', models.DateField()),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
