# Generated by Django 3.1 on 2021-01-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('user_id', models.PositiveIntegerField()),
                ('creation_date', models.DateTimeField(blank=True)),
                ('date_of_update', models.DateTimeField(blank=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField(blank=True, default='')),
                ('liked_users_id', models.TextField(blank=True, default='')),
                ('tags_id', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('moments_id_file', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=300)),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='moments_app.moment')),
            ],
        ),
    ]
