# Generated by Django 3.1 on 2020-12-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moment',
            name='comments_file',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='liked_users_id_file',
        ),
        migrations.RemoveField(
            model_name='moment',
            name='tags_id_file',
        ),
        migrations.AddField(
            model_name='moment',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='moment',
            name='liked_users_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='moment',
            name='tags_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tag',
            name='moments_id_file',
            field=models.TextField(blank=True, default=''),
        ),
    ]
