# Generated by Django 3.1 on 2020-11-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_file', models.TextField(blank=True, null=True)),
                ('user_id', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
