# Generated by Django 3.1 on 2021-01-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_friends', models.TextField(blank=True)),
                ('user_id', models.PositiveIntegerField(unique=True)),
                ('my_friends_q', models.PositiveIntegerField(default=0)),
                ('i_following_q', models.PositiveIntegerField(default=0)),
                ('my_followers_q', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
