# Generated by Django 3.1 on 2020-12-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends_file',
        ),
        migrations.AddField(
            model_name='friend',
            name='user_friends',
            field=models.TextField(blank=True),
        ),
    ]
