# Generated by Django 3.1 on 2020-12-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0002_auto_20201213_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='i_following_q',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friend',
            name='my_followers_q',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='friend',
            name='my_friends_q',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
