# Generated by Django 3.1 on 2020-12-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20201204_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dislikes_user_id',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='likes_user_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
