# Generated by Django 3.1 on 2020-12-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20201206_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
