# Generated by Django 3.1 on 2020-10-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
