# Generated by Django 3.1 on 2020-10-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers_app', '0002_subscriber_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='user_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
